//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExtendedNumerics.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LanguageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExtendedNumerics.Properties.LanguageResources", typeof(LanguageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a positive integer..
        /// </summary>
        public static string Arg_MustBeAPositiveInteger {
            get {
                return ResourceManager.GetString("Arg_MustBeAPositiveInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be greater than or equal to 1.
        /// </summary>
        public static string Arg_MustBeGreaterThanOrEqualToOne {
            get {
                return ResourceManager.GetString("Arg_MustBeGreaterThanOrEqualToOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must be of type {0}.
        /// </summary>
        public static string Arg_MustBeOfType {
            get {
                return ResourceManager.GetString("Arg_MustBeOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must not equal zero..
        /// </summary>
        public static string Arg_MustNotEqualZero {
            get {
                return ResourceManager.GetString("Arg_MustNotEqualZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative precision cannot round left of the decimal point more place values than there are whole number digits..
        /// </summary>
        public static string Arg_NegativePrecision {
            get {
                return ResourceManager.GetString("Arg_NegativePrecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cotangent of π is undefined..
        /// </summary>
        public static string Arithmetic_Trig_Undefined_Cot_Pi {
            get {
                return ResourceManager.GetString("Arithmetic_Trig_Undefined_Cot_Pi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cotangent of zero is undefined..
        /// </summary>
        public static string Arithmetic_Trig_Undefined_Cot_Zero {
            get {
                return ResourceManager.GetString("Arithmetic_Trig_Undefined_Cot_Zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cosecant of π is undefined..
        /// </summary>
        public static string Arithmetic_Trig_Undefined_Csc_Pi {
            get {
                return ResourceManager.GetString("Arithmetic_Trig_Undefined_Csc_Pi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cosecant of zero is undefined..
        /// </summary>
        public static string Arithmetic_Trig_Undefined_Csc_Zero {
            get {
                return ResourceManager.GetString("Arithmetic_Trig_Undefined_Csc_Zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hyperbolic cosecant of zero is undefined..
        /// </summary>
        public static string Arithmetic_Trig_Undefined_Csch_Zero {
            get {
                return ResourceManager.GetString("Arithmetic_Trig_Undefined_Csch_Zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The secant of (2*n + 1)*π/2 (an odd multiple of π/2) is undefined..
        /// </summary>
        public static string Arithmetic_Trig_Undefined_Sec_OddPiOver2 {
            get {
                return ResourceManager.GetString("Arithmetic_Trig_Undefined_Sec_OddPiOver2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tangent of 3π/2 is undefined..
        /// </summary>
        public static string Arithmetic_Trig_Undefined_Tan_3PiOver2 {
            get {
                return ResourceManager.GetString("Arithmetic_Trig_Undefined_Tan_3PiOver2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tangent of π/2 is undefined..
        /// </summary>
        public static string Arithmetic_Trig_Undefined_Tan_PiOver2 {
            get {
                return ResourceManager.GetString("Arithmetic_Trig_Undefined_Tan_PiOver2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value is not a number (NaN)..
        /// </summary>
        public static string NotFinite_NaN {
            get {
                return ResourceManager.GetString("NotFinite_NaN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot raise zero to a negative power..
        /// </summary>
        public static string NotSupported_NegativePower {
            get {
                return ResourceManager.GetString("NotSupported_NegativePower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BigDecimal cannot represent infinity..
        /// </summary>
        public static string Overflow_BigDecimal_Infinity {
            get {
                return ResourceManager.GetString("Overflow_BigDecimal_Infinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BigDecimal is too large for a Decimal..
        /// </summary>
        public static string Overflow_Decimal {
            get {
                return ResourceManager.GetString("Overflow_Decimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BigDecimal is too large for a Double..
        /// </summary>
        public static string Overflow_Double {
            get {
                return ResourceManager.GetString("Overflow_Double", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t parse numerator or denominator..
        /// </summary>
        public static string Overflow_Fraction {
            get {
                return ResourceManager.GetString("Overflow_Fraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BigDecimal is too large for a Int32..
        /// </summary>
        public static string Overflow_Int32 {
            get {
                return ResourceManager.GetString("Overflow_Int32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BigDecimal is too large for a Single..
        /// </summary>
        public static string Overflow_Single {
            get {
                return ResourceManager.GetString("Overflow_Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BigDecimal is too large for a UInt32..
        /// </summary>
        public static string Overflow_UInt32 {
            get {
                return ResourceManager.GetString("Overflow_UInt32", resourceCulture);
            }
        }
    }
}
